# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       AtomicParsley

# >> macros
# << macros

Summary:    MP4 video metadata tool
Version:    0.9.6.20210715
Release:    1
Group:      Applications/Multimedia
License:    GPLv2
URL:        http://github.com/wez/atomicparsley
Source0:    %{name}-%{version}.tar.gz
Source100:  AtomicParsley.yaml
Patch0:     atomicparsley-cmake-3.11.patch
Patch1:     atomicparsley-cmake-runtime-destination.patch
Patch2:     atomicparsley-cmake-cxx11.patch
BuildRequires:  pkgconfig(zlib)
BuildRequires:  cmake
BuildRequires:  automake
Obsoletes:   openrepos-atomicparsley <= 20210114
Obsoletes:   openrepos-atomicparsley <= 0.9.6-1

%description
lightweight command line program for reading, parsing and setting metadata into MPEG-4 files

%prep
%setup -q -n %{name}-%{version}/upstream

# atomicparsley-cmake-3.11.patch
%patch0 -p1
# atomicparsley-cmake-runtime-destination.patch
%patch1 -p1
# atomicparsley-cmake-cxx11.patch
%patch2 -p1
# >> setup
# << setup

%build
# >> build pre
%cmake -Wno-dev -DPACKAGE_VERSION=%{version}-%{release}-SFOS .
%cmake -Wno-dev --build .
# << build pre



# >> build post
make %{?_smp_mflags}
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
%{__install} -D -p -m 755 AtomicParsley %{buildroot}%{_bindir}/AtomicParsley
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
# >> files
# << files
