# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       openrepos-atomicparsley

# >> macros
# << macros

Summary:    AtomicParsley video tool
Version:    20210124
Release:    1
Group:      Applications/Multimedia
License:    GPL
URL:        http://github.com/wez/atomicparsley
Source0:    https://github.com/wez/atomicparsley/archive/20210114.184825.1dbe1be.tar.gz
Source100:  openrepos-atomicparsley.yaml
Patch0:     atomicparsley-cmake-3.11.patch
BuildRequires:  cmake
BuildRequires:  automake

%description
lightweight command line program for reading, parsing and setting metadata into MPEG-4 files

%prep
%setup -q -n %{name}-%{version}

# atomicparsley-cmake-3.11.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
%cmake -Wno-dev -DPACKAGE_VERSION=%{version}-%{release}-SFOS .
%cmake -Wno-dev --build .
# << build pre



# >> build post
make %{?_smp_mflags}
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
%{__install} -D -p -m 755 AtomicParsley $RPM_BUILD_ROOT/%{_bindir}/AtomicParsley
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/AtomicParsley
# >> files
# << files
